export const GET_BLOG_LIST_SUCCESS = 'GET_BLOG_LIST_SUCCESS';
export const GET_BLOG_LIST_FAILURE = 'GET_BLOG_LIST_FAILURE';

export const GET_BLOG_LIST_BY_CATEGORY_SUCCESS = 'GET_BLOG_LIST_BY_CATEGORY_SUCCESS';
export const GET_BLOG_LIST_BY_CATEGORY_FAILURE = 'GET_BLOG_LIST_BY_CATEGORY_FAILURE';

export const GET_BLOG_DETAIL_SUCCESS = 'GET_BLOG_DETAIL_SUCCESS';
export const GET_BLOG_DETAIL_FAILURE = 'GET_BLOG_DETAIL_FAILURE';

export const GET_SEARCH_BLOG_SUCCESS = 'GET_SEARCH_BLOG_SUCCESS';
export const GET_SEARCH_BLOG_FAILURE = 'GET_SEARCH_BLOG_FAILURE';


